channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=25.2
- pip:
  - matplotlib==3.10.6
  - pandas==2.3.2
  - plotly==6.3.0
  - seaborn==0.13.2
  - scikit-learn-1.7.2
  - numpy==1.26.4
  - mlflow==2.16
name: mlflow-env
